#!/usr/bin/python3

"""Flatten the following list to a new list"""

countries = [[('Finland', 'Helsinki')], [('Sweden', 'Stockholm')], [('Norway', 'Oslo')]]

formatted_countries = [[country_name, country_name[:3].upper(), capital_city] for country in countries for country_name, capital_city in country]

print(formatted_countries)

"""This code works by first iterating over the list of countries and the sublist within each country. For each country, the code then creates a new list containing the country name, the country code, and the capital city. The country code is generated by taking the first three characters of the country name and converting them to uppercase.

Finally, the new list is added to the formatted_countries list."


