#!/usr/bin/python3
accessories = ['shoes', 'belt', 'wallet', 'pants', 'vest', 'tshirt', 'boxers']
print(accessories)
print()
print(len(accessories))
print()
print(accessories[::3])
print()
mixed_data_types = ['mbachia', '32', '5\'6\"', 'single', 'kanairo']
it_companies =['Facebook', 'Google', 'Microsoft', 'Apple', 'Oracle', 'Amazon']
print(it_companies)
print(len(it_companies))
print()
print(it_companies[::2])
print()
it_companies.append('Netflix')
print(it_companies)
print()
it_companies.insert(4, 'Dell')
print(it_companies)
print()
# it_companies.isupper('Facebook')
print(it_companies)
print('Facebook' in it_companies)
print()
it_companies.sort()
print(it_companies)
print()
it_companies.reverse()
print(it_companies)
print()
print(len(it_companies))
print()
first_3_sliced = it_companies[3:8]
print(first_3_sliced)
print()
last_3_sliced = it_companies[0:5]
print(last_3_sliced)
print()
middle_sliced = it_companies[:8:3]
print(middle_sliced)
print()
it_companies.remove('Oracle')
print(it_companies)
it_companies.remove('Google')
print(it_companies)
it_companies.remove('Amazon')
print(it_companies)
print()
it_companies.clear()
print(it_companies)
print()
front_end = ['HTML', 'CSS', 'JS', 'React', 'Redux']
back_end = ['Node','Express', 'MongoDB']
all_ends = front_end + back_end
print(all_ends)
full_stack = all_ends.copy()
full_stack.append('Python')
full_stack.append('SQL')
full_stack.append('Redux')
print(full_stack)
print()
